# Generated by Django 4.0.5 on 2022-06-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pariwisata', '0002_kuliner_oleholeh'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
